### PR TITLE
Read source code from subfolder

### PR DESCRIPTION
**Pull request by laseryuan**

### CODE REVIEW

**Comment by mzagorny** [comment]
Hi @laseryuan , thanks for your contribution! Looks useful, but one question - why you need this feature?
I've not seen that GAS supports subfolders

**Comment by laseryuan** [comment]
Thanks @brainysmurf . One of the main reason I prefer to work on gas project locally with gapps (node-google-apps-script) is because of the subfolder support.

**Comment by mzagorny** [comment]
hmm, but how you will use that code in local subfolders after uploading to google?

**Comment by laseryuan** [comment]
After uploaded to google, the file paths get flattened. Just be careful of the file names: https://github.com/danthareja/node-google-apps-script#limitations

**Comment by mzagorny** [comment]
Make sense. thanks for explanation. Will integrate.

**Comment by mTorres** [comment]
Any chance to have this merged? I could use this feature :+1:

**Comment by mzagorny** [comment]
@mTorres thanks for remind! @laseryuan sorry for silence and thanks for patience! Updated version 1.3.0 have been published on npm

**Pull request merged**
